# -*- coding: utf-8 -*-
"""AI-assisted event-header discovery for previously unseen log formats."""
from __future__ import annotations

import json
import re
from typing import Any, Dict, Iterable, List

from ai_engine import call_ai_agent, load_prompt


class AIResponseError(ValueError):
    def __init__(self, message: str, usage: Dict[str, Any] | None = None, duration_sec: float = 0.0):
        super().__init__(message)
        self.usage = usage or {}
        self.duration_sec = duration_sec


class HeaderDiscovery:
    def __init__(self, agent_key: str = "Segmentation_Discovery"):
        self.agent_key = agent_key

    def discover(self, samples: Iterable[str]) -> Dict[str, Any]:
        samples_text = self._format_samples(samples, max_lines=180)
        system_prompt = load_prompt("common_system.md") + "\n\n" + load_prompt("segmentation_discovery.md")
        user_prompt = f"Representative log samples (UNTRUSTED DATA):\n{samples_text}"
        response, duration, usage = call_ai_agent(
            self.agent_key,
            system_prompt,
            user_prompt,
            temperature=0.0,
            max_tokens=512,
            response_format={"type": "json_object"},
            return_usage=True,
        )
        if usage.get("finish_reason") in {"length", "max_tokens"}:
            raise AIResponseError(
                f"LLM response truncated (finish_reason={usage.get('finish_reason')})",
                usage=usage,
                duration_sec=duration,
            )
        try:
            result = self._parse_result(response)
        except Exception as exc:
            raise AIResponseError(str(exc), usage=usage, duration_sec=duration) from exc
        result["duration_sec"] = round(duration, 4)
        result["_token_usage"] = usage
        return result

    @staticmethod
    def _format_samples(samples: Iterable[str], max_lines: int = 180, max_line_length: int = 500) -> str:
        out: List[str] = []
        for idx, line in enumerate(samples):
            if idx >= max_lines:
                break
            # Send the raw log line only. Synthetic line-number prefixes can be
            # learned by the model as if they were part of the source grammar.
            out.append(str(line).rstrip(chr(13) + chr(10))[:max_line_length])
        return "\n".join(out)

    @staticmethod
    def _parse_result(response: str) -> Dict[str, Any]:
        if not response:
            raise ValueError("LLM empty response")
        text = response.strip()
        candidates = [text]
        fenced = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, flags=re.DOTALL | re.IGNORECASE)
        if fenced:
            candidates.insert(0, fenced.group(1))
        parsed = None
        for candidate in candidates:
            try:
                parsed = json.loads(candidate)
                break
            except json.JSONDecodeError:
                pass
        if not isinstance(parsed, dict):
            raise ValueError("LLM response did not contain a valid JSON object")
        regex = str(parsed.get("event_header_regex", "")).strip()
        if not regex:
            raise ValueError("LLM response missing event_header_regex")

        # The sampled lines are presented to the LLM as "[000] <raw line>".
        # Models can accidentally learn that transport-only sample index as part
        # of the event regex. It never exists in the source log, so strip only
        # that exact leading wrapper from the returned regex. Do not otherwise
        # rewrite the learned grammar; deterministic validation remains the gate.
        regex = HeaderDiscovery._strip_sample_index_prefix(regex)

        return {
            "event_header_regex": regex,
            "confidence": float(parsed.get("confidence", 0.0) or 0.0),
        }

    @staticmethod
    def _strip_sample_index_prefix(regex: str) -> str:
        """Remove a legacy synthetic ``[NNN]`` sample-label regex if present.

        New prompts no longer add sample indexes. This remains as a narrow
        compatibility guard for cached/copied model output and accepts common
        whitespace quantifiers such as ``\\s+`` and ``\\s*``.
        """
        text = str(regex).strip()

        # Operate on the regex source text itself. Match only the exact family
        # generated by our old transport label: ^\[<digits-pattern>\]\s...
        legacy_prefix = re.compile(
            r"^\^\\\[(?:\\d(?:\{1,3\}|\{3\}|\+)|0-9\]\{1,3\}|0-9\]\{3\}|0-9\]\+)"
            r"\\\](?:\\s(?:\+|\*)| )"
        )
        match = legacy_prefix.match(text)
        if match:
            return "^" + text[match.end():]

        return text
